#!/bin/sh

# Compile an ICU message bundle (a directory of *.txt resource files) into a
# static archive lib<name>_dat.a using genrb + pkgdata.
#
# Usage: make_message_src.sh <archive_name> [src_bundle_dir] [out_dir]
#   <archive_name>   e.g. libbin_ltfs_dat.a; the bundle name is derived from it
#   [src_bundle_dir] directory holding the *.txt files (default: ./<name>)
#   [out_dir]        directory to write the archive into (default: .)
#
# genrb/pkgdata are taken from $GENRB/$PKGDATA when set (the build system
# passes the paths it discovered); otherwise they are guessed per-OS. This
# script is shared by the autotools and CMake builds: the one-argument form
# preserves the historical in-source layout used by messages/Makefile.am.

set -e

KERNEL_NAME=`uname -s`

# Resolve the ICU tools, honoring the environment first.
if [ "$KERNEL_NAME" = "Darwin" ]; then
	ICU_FRAMEWORK=/Library/Frameworks/ICU.framework
	if [ -d "${ICU_FRAMEWORK}" ]; then
		export PATH="${PATH}:${ICU_FRAMEWORK}/Versions/Current/usr/bin"
		export DYLD_LIBRARY_PATH="${ICU_FRAMEWORK}/Versions/Current/usr/lib"
		: "${GENRB:=${ICU_FRAMEWORK}/Versions/Current/usr/bin/genrb}"
		: "${PKGDATA:=${ICU_FRAMEWORK}/Versions/Current/usr/bin/pkgdata}"
	else
		: "${GENRB:=genrb}"
		: "${PKGDATA:=pkgdata}"
	fi
elif [ "$KERNEL_NAME" = "FreeBSD" ]; then
	: "${GENRB:=genrb}"
	: "${PKGDATA:=/usr/local/bin/pkgdata}"
else
	if [ -x /usr/bin/genrb ]; then : "${GENRB:=/usr/bin/genrb}"; else : "${GENRB:=genrb}"; fi
	if [ -x /usr/bin/pkgdata ]; then : "${PKGDATA:=/usr/bin/pkgdata}"; else : "${PKGDATA:=pkgdata}"; fi
fi

if [ "$#" -lt "1" ]; then
	echo "Usage: $0 archive_name [src_bundle_dir] [out_dir]"
	exit 1
fi

case $KERNEL_NAME in
	MINGW32_NT*)
		BASENAME=`echo $1 | sed -e 's/_dat\.o$//'`
		;;
	*)
		BASENAME=`echo $1 | sed -e 's/_dat\.a$//'`
		BASENAME=`echo $BASENAME | sed -e 's/^lib//'`
		;;
esac

# Source bundle dir and output dir default to the historical in-source layout.
SRC_DIR=${2:-./${BASENAME}}
OUT_DIR=${3:-.}
mkdir -p "$OUT_DIR"
OUT_DIR=`cd "$OUT_DIR" && pwd`           # absolute, survives the work-dir cd
SRC_DIR=`cd "$SRC_DIR" && pwd`

make_obj() {
	echo "Processing ${BASENAME}"

	WORK="${OUT_DIR}/.work-${BASENAME}"
	rm -rf "$WORK"
	mkdir -p "$WORK"

	# Generate the resource files, then package them statically.
	${GENRB} -d "$WORK" -q "${SRC_DIR}"/*.txt
	( cd "$WORK" && ls *.res > packagelist.txt && \
	  ${PKGDATA} -p ${BASENAME} -m static -q packagelist.txt >/dev/null )

	case $KERNEL_NAME in
		MINGW32_NT*)
			mv "$WORK/${BASENAME}.dat" "$OUT_DIR/"
			;;
		FreeBSD)
			# pkgdata -m static produces an ar(1) archive with several
			# object files on FreeBSD; rename it to the regular convention.
			mv "$WORK/lib${BASENAME}.a" "$OUT_DIR/lib${BASENAME}_dat.a"
			;;
		NetBSD)
			# Generate a libtool archive for later linking.
			mv "$WORK/lib${BASENAME}.a" "$OUT_DIR/lib${BASENAME}_dat.a"
			OBJFILE=${BASENAME}_dat.o
			LTFILE=${BASENAME}_dat.lo
			mkdir -p "$WORK/.libs" "$OUT_DIR/.libs"
			mv "$WORK/${OBJFILE}" "$WORK/.libs"
			LTVERS=`libtool --version |
			    sed -e 's/^\([^ ]*\) (GNU \(.*\)) \(.*\)$$/\1 - GNU \2 \3/' -e q`
			echo "# ${OBJFILE} - a libtool object file" > "$OUT_DIR/${LTFILE}"
			echo "# Generated by ${LTVERS}" >> "$OUT_DIR/${LTFILE}"
			echo "pic_object='.libs/${OBJFILE}'" >> "$OUT_DIR/${LTFILE}"
			echo "non_pic_object=none" >> "$OUT_DIR/${LTFILE}"
			cp "$WORK/.libs/${OBJFILE}" "$OUT_DIR/.libs/"
			( cd "$OUT_DIR" && libtool --mode=link --tag=CC cc -o "lib${BASENAME}_dat.la" "${LTFILE}" )
			cp "$OUT_DIR/lib${BASENAME}_dat.a" "$OUT_DIR/.libs"
			;;
		*)
			mv "$WORK/${BASENAME}_dat.o" "$OUT_DIR/lib${BASENAME}_dat.a"
			;;
	esac

	rm -rf "$WORK"
}

# Rebuild only when a source file is newer than the existing archive.
OUT_FILE="$OUT_DIR/$1"
if [ -f "$OUT_FILE" ]; then
	for file in "$SRC_DIR"/*.txt; do
		if [ "$file" -nt "$OUT_FILE" ]; then
			make_obj
			exit 0
		fi
	done
else
	make_obj
fi
