#
# Set the tape backend and set default in case is not defined
#
macro(option_tape_backend)
	if (NOT DEFAULT_TAPE)
		if(LINUX)
			set(DEFAULT_TAPE sg)
		elseif(APPLE)
			set(DEFAULT_TAPE iokit)
		elseif(BSD)
			if(FREEBSD)
				set(DEFAULT_TAPE cam)
			elseif(NETBSD)
				set(DEFAULT_TAPE scsipi-ibmtape)
			endif()
		endif()
	elseif (NOT ENABLE_LINTAPE AND DEFAULT_TAPE STREQUAL "lin_tape")
		message(FATAL_ERROR "lin_tape is not enabled -DENABLE_LINTAPE is required.")
	endif()
endmacro()

macro(option_unorm2)
	string(REPLACE "." ";" ICU_VERSION_ARRAY ${ICU_VERSION})
	list(GET ICU_VERSION_ARRAY 0 ICU_VERSION_MAJOR)
	if(ICU_6X OR ICU_VERSION_MAJOR GREATER_EQUAL "56")
		add_compile_definitions(USE_UNORM2)
		message(STATUS "Using ICU6x funtions")
	endif()
endmacro()
