name: CentOS Build Jobs

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'docker://centos:centos7' ]

    steps:
      - run: uname -a
