name: Ubuntu 19.10 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu Eoan
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/Ubuntu1910-Build@v1.0
        with:
          destination: '/tmp/ltfs'
