name: CentOS Build Jobs

on: [push, pull_request]

jobs:
  build:
    name: Build on CentOS
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - uses: ./ # Uses an action in the root directory
      - name: Hello world action step
        id: hello
        uses: actions/CentOS-Build@v0.1
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
