name: CentOS Build Jobs

on: [push, pull_request]

jobs:
  build:
    name: Build on CentOS
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/CentOS-Build@v0.3
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.build.outputs.time }}"
