name: Ubuntu 16.04 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu Xeneal
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: package setup
      run: apt -y update && apt -y upgrade && apt -y install libfuse-dev libxml2-dev
    - name: configure
      run: ./autogen.sh && ./configure
    - name: make
      run: make
