name: Ubuntu 16.04 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu Xeneal
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
