name: CentOS8 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on CentOS8
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/CentOS8-Build@v1.3
        with:
          destination: '/tmp/ltfs'
