name: Ubuntu 16.04 Build Job

on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu Xeneal
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Build LTFS
        id: build
        uses: LinearTapeFileSystem/Ubuntu1604-Build@v1.0
        with:
          destination: '/tmp/ltfs'
